#  EssentialServer by CoachL_ck
#  For help on configuration or in general, please check the wiki.
#  Link: https://github.com/CoachLuck/EssentialServer/wiki
check-updates: true

# The message to send the player when they do not have permission
permission-message: '&cYou do not have permission to use this command!'

# Offline player message
offline-player: "&c%player% &7is currently offline!"

# # # # # # # # # # # # # # # # # # # # # # # # # # #
#           Player Join - Leave Messages            #
# enable-message, (True) enables command messages,  #
# (False) disable command messages                  #
# # # # # # # # # # # # # # # # # # # # # # # # # # #
Join-Leave:
  join-message: '&7Welcome, &c%player%&7, to the server!'
  leave-message: '&7Adios, &c%player%&7, see you soon!'
  enabled: true

# # # # # # # # # # # # # # # # # # # # # # # # #
#                Spawn Settings                 #
# Spawn - Sets to specific coordinates and saves #
# Use /setspawn to set this perfectly           #
# @ yaw is horizontal view, @ pitch is vertical #
# # # # # # # # # # # # # # # # # # # # # # # # #
spawn:
  world: null
  x: null
  y: null
  z: null
  yaw: null
  pitch: null
  spawn-message: '&eWhoosh... &7You have respawned!'
  other-message: '&7You have sent &e%player% &7to the spawn.'
  enable-message: true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                    Gamemode messages                            #
# message: %mode% is the gamemode the user is switching too                       #
# message-others: %player% the player the user is changing the name of            #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
gamemode:
  message: '&7Gamemode has been switched to &b%mode%&7.'
  message-others: '&7You have changed the game mode of &e%player% &7to &b%mode%.'
  message-enable: true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                Feed messages and amount.                        #
# amount: (0 - 20) - controls how much a player gets fed when they do /feed.      #
# other-message: %player% - the player the user is feading                        #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
feed:
  amount: 20
  message: '&7You have been &a&lfed&r&7!'
  other-message: '&7You have &a&lfed &e&l%player%&r&7!'
  message-enable: true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                               Heal messages and amount.                         #
# amount: (0 - 20) - controls how much a player gets healed when they do /heal    #
# other-message: %player% - the player the user is feading                        #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
heal:
  amount: 20
  message: '&7You have been &a&lhealed&r&7!'
  other-message: '&7You have healed &e&l%player%&r&7!'
  message-enable: true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                             Teleportation placeholders                                                    #
# cooldown-time: Any number, Set this to 0 to disable, or give users essentialserver.teleport.bypass to let them bypass it  #
# cooldown-message: %time% - this will show the time remaining in the cooldown                                              #
# message: %player% - the player you are teleporting too                                                                    #
# others-message: %player1% the player you are teleporting, %player2% - the player that is being teleported too             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
teleport:
  cooldown-time: 5
  cooldown-message: "&7You currently have a &cTeleport Cooldown &7for &e%time% seconds&7."
  self: "&cYou can't teleport to yourself..."
  message: '&7You have &ateleported &7to &c%player%&7!'
  others-message: '&7You have teleported &e%player1% &7to &e%player2%&7!'
  message-enable: true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                               Burn Placeholders                                 #
# burn-time: int amount of seconds of which they player should be on fire for     #
# others-message: %player%, replaces with the name of the player you are burning  #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
burn:
  burn-time: 5
  message: '&7You have been &c&lset on fire&r&7!'
  others-message: '&7You have set &c%player%&r&7 on fire!'
  self-message: '&7You have set &cYourself??&r&7 on fire!'
  message-enable: true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                               Rest of Config                            #
# others-message: %player%, the player you are performing the command on  #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
smite:
  message: '&7You have been &e&lSTRUCK&r &7 with &e&nlightning&r&7!'
  others-message: '&7You have struck &e&l%player%&r&7 with lightning!'
  self-message: '&7You have struck &e&lYourself??&r&7 with lightning!'
  message-enable: true
kill:
  message: '&cYou have been &c&lkilled&r&c!'
  others-message: '&cYou have &c&lkilled &e%player%&r&c!'
  suicide-message: '&cYou have committed &c&lsuicide&r&c!'
  message-enable: true
clear:
  message: '&7Your inventory has been &a&lcleared&r&7!'
  others-message: '&7You have &a&lcleared&r&7 the inventory of &e&l%player%&r&7!'
  message-enable: true
fly:
  on-message: '&7Flight has been &a&lenabled&r&7!'
  off-message: '&7Flight has been &c&ldisabled&r&7!'
  other-on-message: '&7Flight has been &a&lenabled&r&7 for &e&l%player%&r&7!'
  other-off-message: '&7Flight has been &c&ldisabled&r&7 for &e&l%player%&r&7!'
  message-enable: true
god:
  on-message: '&7God mode has been &a&lenabled&r&7!'
  off-message: '&7God mode has been &c&ldisabled&r&7!'
  others-on-message: '&7God mode has been &a&lenabled&r&7 for &e&l%player%&r&7!'
  others-off-message: '&7God mode has been &c&ldisabled&r&7 for &e&l%player%&r&7!'
  message-enable: true
vanish:
  on-message: '&7Vanish has been &a&lenabled&r&7!'
  off-message: '&7Vanish has been &c&ldisabled&r&7!'
  other-on-message: '&7Vanish has been &a&lenabled&r&7 for &e&l%player%&r&7!'
  other-off-message: '&7Vanish has been &c&ldisabled&r&7 for &e&l%player%&r&7!'
  message-enable: true
invsee:
  message: '&aYou have opened the inventory of &7%player%&a!'
  message-enable: true