permission-message: "&cYou do not have permission to use this command!"
feed:
  amount: 20
  message: "&bYou have been fed."
  message-enable: false
  title: "&bMunch.. Munch.. Munch.."
  sub-title: "&aYou have been fed!"
  title-fade: 4
  title-stay: 8
  title-enable: false
heal:
  amount: 0
  message: "&bYou have been healed."
  message-enable: true
  title: ""
  sub-title: ""
  title-fade: 4
  title-stay: 8
  title-enable: false
teleport:
  amount:
  message: "&cInsert messaged"
  message-enable: true
  title: ""
  sub-title: ""
  title-fade: 4
  title-stay: 8
  title-enable: false
kill:
  message: "&cYou have been killed!"
  others-message: "You have killed "
  suicide-message: "&cWhy have you done this!"
  message-enable: true
command:
  amount: 0
  message: "&cInsert messaged"
  message-enable: true
  title: ""
  sub-title: ""
  title-fade: 4
  title-stay: 8
  title-enable: false
clear:
  message: "&bYour inventory has been cleared!"
  clear-others-message: "&bYou have cleared the inventory of "
  message-enable: true