# The message to send the player when they do not have permission
permission-message: '&cYou do not have permission to use this command!'

# Offline player message
offline-player: "&c%player% &7is currently offline!"

# # # # # # # # # # # # # # # # # # # # # # # # # # #
#           Player Join - Leave Messages            #
# enable-message, (True) enables command messages,  #
# (False) disable command messages                  #
# # # # # # # # # # # # # # # # # # # # # # # # # # #
join-message: '&bWelcome, &6%player%&b, to the server!'
leave-message: '&bAdios, &6%player%&b, see you soon!'
enable-message: true

# # # # # # # # # # # # # # # # # # # # # # # # #
#                Spawn Settings                 #
# Spawn - Sets to specific coordinates and saves #
# Use /setspawn to set this perfectly           #
# @ yaw is horizontal view, @ pitch is vertical #
# # # # # # # # # # # # # # # # # # # # # # # # #
spawn:
  world: null
  x: null
  y: null
  z: null
  yaw: null
  pitch: null
  spawn-message: '&eWhoosh... &6You have respawned!'
  enable-message: true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                    Gamemode messages                            #
# message: %mode% is the gamemode the user is switching too                       #
# message-others: %player% the player the user is changing the name of            #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
gamemode:
  message: '&7Gamemode has been switched to &b%mode%&7.'
  message-others: '&7You have changed the game mode of &b%player% &7to &e%mode%.'
  message-enable: true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                Feed messages and amount.                        #
# amount: (0 - 20) - controls how much a player gets fed when they do /feed.      #
# other-message: %player% - the player the user is feading                        #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
feed:
  amount: 20
  message: '&bYou have been &a&lfed&r&b!'
  other-message: '&bYou have &a&lfed &6&l%player%&r&b!'
  message-enable: true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                               Heal messages and amount.                         #
# amount: (0 - 20) - controls how much a player gets healed when they do /heal    #
# other-message: %player% - the player the user is feading                        #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
heal:
  amount: 20
  message: '&bYou have been &a&lhealed&r&b!'
  other-message: '&bYou have healed &6&l%player%&r&b!'
  message-enable: true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                             Teleportation placeholders                                                    #
# cooldown-time: Any number, Set this to 0 to disable, or give users essentialserver.teleport.bypass to let them bypass it  #
# cooldown-message: %time% - this will show the time remaining in the cooldown                                              #
# message: %player% - the player you are teleporting too                                                                    #
# others-message: %player1% the player you are teleporting, %player2% - the player that is being teleported too             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
teleport:
  cooldown-time: 5
  cooldown-message: "&cCool-Down: &6%time% seconds &cremaining."
  self: "&cYou can't teleport to yourself..."
  message: '&7You have &6teleported &7to &b%player%&7!'
  others-message: '&7You have teleported &b%player1% &7to &b%player2%&7!'
  message-enable: true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                               Burn Placeholders                                 #
# burn-time: int amount of seconds of which they player should be on fire for     #
# others-message: %player%, replaces with the name of the player you are burning  #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
burn:
  burn-time: 5
  message: '&cYou have been &4&lset on fire&r&c!'
  others-message: '&cYou have set &4&l&6&l%player%&r&c on fire!'
  self-message: '&cYou have set &4&lYourself??&r&c on fire!'
  message-enable: true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                               Rest of Config                            #
# others-message: %player%, the player you are performing the command on  #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
smite:
  message: '&6You have been &e&lSTRUCK&r &6with &e&nlightning&r&6!'
  others-message: '&6You have struck &e&l%player%&r&6 with lightning!'
  self-message: '&6You have struck &e&lYourself??&r&6 with lightning!'
  message-enable: true
kill:
  message: '&cYou have been &4&lkilled&r&c!'
  others-message: '&cYou have &4&lkilled &6&l%player%&r&c!'
  suicide-message: '&cYou have committed &4&lsuicide&r&c!'
  message-enable: true
clear:
  message: '&bYour inventory has been &a&lcleared&r&b!'
  others-message: '&bYou have &a&lcleared&r&b the inventory of &6&l%player%&r&b!'
  message-enable: true
fly:
  on-message: '&bFlight has been &a&lenabled&r&b!'
  off-message: '&bFlight has been &c&ldisabled&r&b!'
  other-on-message: '&bFlight has been &a&lenabled&r&b for &6&l%player%&r&b!'
  other-off-message: '&bFlight has been &c&ldisabled&r&b for &6&l%player%&r&b!'
  message-enable: true
god:
  on-message: '&bGod mode has been &a&lenabled&r&b!'
  off-message: '&bGod mode has been &c&ldisabled&r&b!'
  others-on-message: '&bGod mode has been &a&lenabled&r&b for &6&l%player%&r&b!'
  others-off-message: '&bGod mode has been &c&ldisabled&r&b for &6&l%player%&r&b!'
  message-enable: true
vanish:
  on-message: '&bVanish has been &a&lenabled&r&b!'
  off-message: '&bVanish has been &c&ldisabled&r&b!'
  other-on-message: '&bVanish has been &a&lenabled&r&b for &6&l%player%&r&b!'
  other-off-message: '&bVanish has been &c&ldisabled&r&b for &6&l%player%&r&b!'
  message-enable: true
invsee:
  message: '&aYou have opened the inventory of &b%player%&a!'
  message-enable: true