name: EssentialServer
version: 1.0.0-ALPHA
main: io.github.coachluck.EssentialServer
commands:
  command:
    description: placeholder
    usage: /<command>

  feed:
    description: "Fill your tummy with some invisible food."
    usage: /<command>
    permission: essentialserver.feed
  god:
    description: "Become absolutley invincible, not even thanos could stop you."
    usage: /<command>
    permission: essentialserver.god
  heal:
    description: "Heals the player or yourself if left unspecified."
    usage: /<command>
    permission: essentialserver.heal
  eshelp:
    description: "Displays plugin information."
    usage: /<command> <arg0>
    alias: [es, help, essentialserver, esh]
  kill:
    description: "Makes you do the unspeakable..."
    usage: /<command>
    permission: essentialserver.kill