name: EssentialServer
version: 1.0.0-ALPHA
main: io.github.coachluck.EssentialServer
load: STARTUP
commands:
  esreload:
    description: "Reload's Essential Server's configuration"
    permission: essentialserver.reload
    usage: /<command>
  clear:
    description: "Clears your inventory or the player specified."
    aliases: [ci, clearinv, clearinventory]
    usage: /<command> [player]
    permission: essentialserver.clear
  feed:
    description: "Fill your tummy with some invisible food."
    usage: /<command> [player]
    permission: essentialserver.feed
  god:
    description: "Become absolutley invincible, not even thanos could stop you."
    usage: /<command> [player]
    permission: essentialserver.god
  heal:
    description: "Heals the player or yourself if left unspecified."
    usage: /<command> [player]
    permission: essentialserver.heal
  eshelp:
    description: "Displays plugin information."
    alias: [essentialserver, esh]
    permission: essentialserver.eshelp
  kill:
    description: "Makes you do the unspeakable..."
    permission: essentialserver.kill
    usage: /<command> [player]
  fly:
    description: "Makes you take flight."
    permission: essentialserver.fly
    usage: /<command> [player]
  invsee:
    description: "Opens the specified players inventory."
    usage: /<command> [player]
    permission: essentialserver.invsee
  vault:
    description: "Opens a players vault."
    usage: /<command> [player]
  freeze:
    description: "Freezes the specified player."
    usage: /<command> (player)
permissions:
  essentialserver.*:
    description: "Give access to all Essential Server commands"
    children:
      essentialserver.eshelp: true
      essentialserver.kill: true
      essentialserver.kill.others: true
      essentialserver.heal: true
      essentialserver.heal.others: true
      essentialserver.feed: true
      essentialserver.feed.others: true
      essentialserver.god: true
      essentialserver.god.others: true
      essentialserver.clear: true
      essentialserver.clear.others: true
      essentialserver.fly: true
      essentialserver.fly.others: true
      essentialserver.esreload: true
  essentialserver.eshelp:
    description: "Displays plugin information."
    default: op
  essenitalserver.esreload:
    description: "Reloads the configuration files"
    default: op
  essentialserver.kill:
    description: "Allows you to kill yourself!"
  essentialserver.kill.others:
    description: "Allows you to kill others!"
    default: op
    children:
      essentialserver.kill: true
  essentialserver.heal:
    description: "Allows you to heal yourself."
  essentialserver.heal.others:
    description: "Allows you to heal others!"
    default: op
    children:
      essentialserver.heal: true
  essentialserver.feed:
    description: "Allows you to feed yourself."
    essentialserver.feed.others:
      description: "Allows you to feed others!"
      default: op
      children:
        essentialserver.feed: true
  essentialserver.god:
    description: "Allows you to become invincible."
    essentialserver.god.others:
      description: "Allows you to make others invincible!"
      default: op
      children:
        essentialserver.god: true
  essentialserver.clear:
    description: "Allows you to clear your inventory."
  essentialserver.clear.others:
    description: "Allows you to clear the inventory of other players!"
    default: op
    children:
      essentialserver.clear: false
  essentialserver.fly:
    description: "Allows you to take flight!"
  essentialserver.fly.others:
    description: "Make others take flight!"
    default: op
    children:
      essentialserver.fly: true
  essentialserver.invsee:
    description: "Allows you to take a peak into other players inventories!"
    default: op
  essentialserver.invsee.interact:
    description: "Allows you to interact with other players inventories!"