name: EssentialServer
version: 1.0.0-ALPHA
main: io.github.coachluck.EssentialServer
commands:
  command:
    description: placeholder
    usage: /<command>
  clear:
    description: "Clears your inventory or the player specified."
    permission: essentialserver.clear
    aliases: [ci, clearinv, clearinventory]
    usage: /<command> [player]
  feed:
    description: "Fill your tummy with some invisible food."
    permission: essentialserver.feed
  god:
    description: "Become absolutley invincible, not even thanos could stop you."
    permission: essentialserver.god
  heal:
    description: "Heals the player or yourself if left unspecified."
    permission: essentialserver.heal
  eshelp:
    description: "Displays plugin information."
    alias: [essentialserver, esh]
  kill:
    description: "Makes you do the unspeakable..."
    permission: essentialserver.kill
    usage: /<command> [player]
