name: EssentialServer
version: 1.0
main: io.github.coachluck.EssentialServer
load: STARTUP
commands:
  clear:
    description: "Clears your inventory or the player specified."
    aliases: [ci, clearinv, clearinventory]
    usage: /<command> [player]
    permission: essentialserver.clear
  feed:
    description: "Fill your tummy with some invisible food."
    usage: /<command> [player]
    permission: essentialserver.feed
  god:
    description: "Become absolutley invincible, not even thanos could stop you."
    usage: /<command> [player]
    permission: essentialserver.god
  heal:
    description: "Heals the player or yourself if left unspecified."
    usage: /<command> [player]
    permission: essentialserver.heal
  kill:
    description: "Makes you do the unspeakable..."
    usage: /<command> [player]
    permission: essentialserver.kill
  fly:
    description: "Makes you take flight."
    usage: /<command> [player]
    permission: essentialserver.fly
  invsee:
    description: "Opens the specified players inventory."
    usage: /<command> [player]
    permission: essentialserver.invsee
  burn:
    description: "Burns you or the specified player!"
    aliases: [burnplayer, b]
    usage: /<command> [player]
    permission: essentialserver.burn
  smite:
    description: "Strikes you or the specified player with a glistening beam of lightning!"
    aliases: [thor, lightning]
    usage: /<command> [player]
    permission: essentialserver.smite
  spawn:
    description: "Teleports the player to the spawnpoint."
    usage: /<command> [player]
    permission: essentialserver.spawn
  vanish:
    description: "Become invisible!"
    usage: /<command> [player]
    permission: essentialserver.vanish
  setspawn:
    description: "Set the spawn location!"
    usage: /<command>
    permission: essentialserver.setspawn
permissions:
  essentialserver.*:
    description: "Give access to all Essential Server commands"
    children:
      essentialserver.eshelp: true
      essentialserver.smite: true
      essentialserver.kill: true
      essentialserver.kill.others: true
      essentialserver.heal: true
      essentialserver.heal.others: true
      essentialserver.feed: true
      essentialserver.feed.others: true
      essentialserver.god: true
      essentialserver.god.others: true
      essentialserver.clear: true
      essentialserver.clear.others: true
      essentialserver.fly: true
      essentialserver.fly.others: true
      essentialserver.esreload: true
      essentialserver.tp: true
      essentialserver.burn: true
      essentialserver.burn.others: true
      essentialserver.spawn: true
      essentialserver.spawn.others: true
      essentialserver.vanish: true
      essentialserver.vanish.others: true

  essentialserver.eshelp:
    description: "Displays plugin information."
    default: op
  essentialserver.kill:
    description: "Allows you to kill yourself!"
  essentialserver.kill.others:
    description: "Allows you to kill others!"
    default: op
    children:
      essentialserver.kill: true
  essentialserver.heal:
    description: "Allows you to heal yourself."
  essentialserver.heal.others:
    description: "Allows you to heal others!"
    default: op
    children:
      essentialserver.heal: true
  essentialserver.feed:
    description: "Allows you to feed yourself."
  essentialserver.feed.others:
    description: "Allows you to feed others!"
    default: op
    children:
      essentialserver.feed: true
  essentialserver.god:
    description: "Allows you to become invincible."
    essentialserver.god.others:
      description: "Allows you to make others invincible!"
      default: op
      children:
        essentialserver.god: true
  essentialserver.clear:
    description: "Allows you to clear your inventory."
  essentialserver.clear.others:
    description: "Allows you to clear the inventory of other players!"
    default: op
    children:
      essentialserver.clear: true
  essentialserver.fly:
    description: "Allows you to take flight!"
  essentialserver.fly.others:
    description: "Make others take flight!"
    default: op
    children:
      essentialserver.fly: true
  essentialserver.vanish:
    description: "Become completley invisible!"
  essentialserver.vanish.others:
    description: "Make others become invisible!"
    default: op
    children:
      essentialserver.vanish: true
  essentialserver.tp:
    description: "Teleports you to the specified player"
  essentialserver.tp.others:
    description: "Teleports the first player specified to the second player specified"
    default: op
    children:
      essentialserver.tp: true
  essentialserver.invsee:
    description: "Allows you to take a peak into other players inventories!"
    default: op
  essentialserver.invsee.interact:
    description: "Allows you to interact with other players inventories!"
  essentialserver.spawn:
    description: "Allows you to visit the spawn point."
  essentialserver.spawn.others:
    description: "Allows you to make others teleport to the spawn point."
    default: op
    children:
      essentialserver.spawn: true
  essentialserver.setspawn:
    description: "Allows you to set the spawn point!"
    default: op
  essentialserver.smite:
    description: "Allows you to smite yourself!"
  essentialserver.smite.others:
    description: "Allows you to smite others!"
    default: op
    children:
      essentialserver.smite: true