name: EssentialServer
api-version: 1.15
version: 1.2.8
main: io.github.coachluck.EssentialServer
load: POSTWORLD
commands:
  es:
    description: "Basic plugin information."
    aliases: [esinfo, essentialserver, essentials]
    usage: /es
    permission: essentialserver.info
  eshelp:
    description: "Shows the basic help for commands in this plugin."
    usage: /eshelp
    permission: essentialserver.help
  clear:
    description: "Clears your inventory or the player specified."
    aliases: [ci, clearinv, clearinventory]
    usage: /clear [player]
    permission: essentialserver.clear
  feed:
    description: "Fill your tummy with some invisible food."
    usage: /feed [player]
    permission: essentialserver.feed
  god:
    description: "Makes you or the player completely invincible."
    usage: /god [player]
    permission: essentialserver.god
  heal:
    description: "Heal yourself or the player specified."
    usage: /heal [player]
    permission: essentialserver.heal
  kill:
    description: "Kill yourself or the player specified."
    usage: /kill [player]
    permission: essentialserver.kill
  fly:
    description: "Makes you or the player take flight."
    usage: /fly [player]
    permission: essentialserver.fly
  teleport:
    description: "Teleports you to the specified player or teleports player1 to player2"
    usage: /teleport [player1] <player2>
    aliases: [tp]
    permission: essentialserver.tp
  burn:
    description: "Burns you or the specified player."
    aliases: [burnplayer, b]
    usage: /burn [player]
    permission: essentialserver.burn
  smite:
    description: "May the power of thor be bestowed upon you."
    aliases: [thor, lightning]
    usage: /smite [player]
    permission: essentialserver.smite
  spawn:
    description: "Teleports you or the player to spawn."
    usage: /spawn [player]
    permission: essentialserver.spawn
  vanish:
    description: "Become invisible to everyone on the server!"
    usage: /vanish [player]
    permission: essentialserver.vanish
  setspawn:
    description: "Set the spawn for the server."
    usage: /setspawn
    permission: essentialserver.setspawn
  gamemode:
    description: "Changes your gamemode or the player."
    usage: /gamemode <mode> [player]
    permission: essentialserver.gamemode
    aliases: [gm]
  invsee:
    description: "Allows you to look inside of players inventory"
    usage: /invsee <player>
    permission: essentialserver.invsee
  warp:
    description: "Teleport to the specified warp"
    usage: /warp <warp>
    permission: essentialserver.warp
    aliases:
      - warps
  setwarp:
    description: "Add your current location as a warp"
    usage: /setwarp <name>
    permission: essentialserver.setwarp
    aliases:
      - addwarp
      - newwarp
  delwarp:
    description: "Delete a warp"
    usage: /delwarp <warp>
    permission: essentialserver.delwarp
    aliases:
      - deletewarp
      - removewarp
permissions:
  essentialserver.*:
    description: "Give access to all Essential Server commands"
    children:
      essentialserver.es: true
      essentialserver.gamemode: true
      essentialserver.gamemode.others: true
      essentialserver.help: true
      essentialserver.smite: true
      essentialserver.smite.others: true
      essentialserver.kill: true
      essentialserver.kill.others: true
      essentialserver.heal: true
      essentialserver.heal.others: true
      essentialserver.feed: true
      essentialserver.feed.others: true
      essentialserver.god: true
      essentialserver.god.others: true
      essentialserver.clear: true
      essentialserver.clear.others: true
      essentialserver.fly: true
      essentialserver.fly.others: true
      essentialserver.burn: true
      essentialserver.burn.others: true
      essentialserver.spawn: true
      essentialserver.spawn.others: true
      essentialserver.vanish: true
      essentialserver.vanish.others: true
      essentialserver.tp: true
      essentialserver.tp.others: true
      essentialserver.tp.bypass: true
      essentialserver.invsee: true
      essentialserver.warp: true
      essentialserver.setwarp: true
      essentialserver.delwarp: true

  essentialserver.info:
    description: "Display author information"
    defualt: op
  essentialserver.help:
    description: "Displays plugin information."
    default: op
  essentialserver.kill:
    description: "Allows you to kill yourself!"
    default: op
  essentialserver.kill.others:
    description: "Allows you to kill others!"
    default: op
    children:
      essentialserver.kill: true
  essentialserver.heal:
    description: "Allows you to heal yourself."
    defualt: op
  essentialserver.heal.others:
    description: "Allows you to heal others!"
    default: op
    children:
      essentialserver.heal: true
  essentialserver.feed:
    description: "Allows you to feed yourself."
    defualt: op
  essentialserver.feed.others:
    description: "Allows you to feed others!"
    default: op
    children:
      essentialserver.feed: true
  essentialserver.god:
    description: "Allows you to become invincible."
    defualt: op
    essentialserver.god.others:
      description: "Allows you to make others invincible!"
      default: op
      children:
        essentialserver.god: true
  essentialserver.clear:
    description: "Allows you to clear your inventory."
    defualt: op
  essentialserver.clear.others:
    description: "Allows you to clear the inventory of other players!"
    default: op
    children:
      essentialserver.clear: true
  essentialserver.fly:
    description: "Allows you to take flight!"
  essentialserver.fly.others:
    description: "Make others take flight!"
    default: op
    children:
      essentialserver.fly: true
  essentialserver.vanish:
    description: "Become completley invisible!"
    defualt: op
  essentialserver.vanish.others:
    description: "Make others become invisible!"
    default: op
    children:
      essentialserver.vanish: true
  essentialserver.tp:
    description: "Teleports you to the specified player"
    defualt: op
  essentialserver.tp.others:
    description: "Teleports the first player specified to the second player specified"
    default: op
    children:
      essentialserver.tp: true
  essentialserver.tp.bypass:
    description: "Allows you to bypass the teleport cooldown"
    default: op
  essentialserver.spawn:
    description: "Allows you to visit the spawn point."
    defualt: op
  essentialserver.spawn.others:
    description: "Allows you to make others teleport to the spawn point."
    default: op
    children:
      essentialserver.spawn: true
  essentialserver.setspawn:
    description: "Allows you to set the spawn point!"
    default: op
  essentialserver.smite:
    description: "Allows you to smite yourself!"
    default: op
  essentialserver.smite.others:
    description: "Allows you to smite others!"
    default: op
    children:
      essentialserver.smite: true
  essentialserver.gamemode:
    description: "Allows you to change your gamemode!"
    default: op
  essentialserver.gamemode.others:
    description: "Allows you to change another players gamemode!"
    default: op
    children:
      essentialserver.gamemode: true
  essentialserver.invsee:
    description: "Allows you to view a players inventory"
    default: op
  essentialserver.warp:
    description: "Allows a player to warp to a location"
    default: op
  essentialserver.setwarp:
    description: "Allows you to set and create new warps"
    default: op
    children:
      essentialserver.warp: true
  essentialserver.delwarp:
    description: "Allows you to delete a warp"
    default: op
    children:
      essentialserver.warp: true
